### ISSUE TITLE
How can I set up next build?

### ISSUE THREAD

**Issue by ilyadynin** [ixartz/Next-JS-Landing-Page-Starter-Template#3]
I want to set up i18n for this landingpage, but this requires next build and a node.js server -> I set the build command to next build but it doesn't work, so what should I do?

**Comment by ilyadynin** [comment]
And I also would like to add the google tag manager, but I am failing - I am really new to next.js so I am really sorry :c

**Comment by ixartz** [comment]
Next JS has i18n support: https://nextjs.org/docs/advanced-features/i18n-routing
You should use it as a starting point.

Sorry, your two issues aren't very related to the project, the issue is more related to Next JS in general. You should ask on the official Next JS repo.
I haven't the opportunity to try either i18n or either Google tag manager in my Next JS project, couldn't share any experience with it.
